services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - "start-dev"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapp:
    build:
      context: ./webapp
    container_name: webapp2
    ports:
      - "5000:5000"
    depends_on:
      - keycloak

volumes:
  keycloak-data:
  postgres-data:
