spring:
  logging:
    level:
      org:
        springframework:
          security: DEBUG
  application:
    name: demo
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID_SSD}
            client-secret: ${GOOGLE_CLIENT_SECRET_SSD}
            scope:
              - profile
              - email
            redirect-uri: https://localhost:8443/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: Google
          keycloak:
            client-id: my-webapp
            client-secret: cQdQG9sBhsLjhBVIaZB05QjK05zS7DhD
            scope:
              - openid
              - profile
              - email
            redirect-uri: "https://localhost:8443/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
            client-name: Keycloak
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          keycloak:
            issuer-uri: http://localhost:8080/realms/ProgettoSSD

server:
  port: 8443
  ssl:
    key-store: file:C:/Users/hp/Documents/Esami In Corso/System Sec/Homework/SysSec/HW6/demo/src/main/resources/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: selfsigned
    ssl.protocol: TLS