services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "ExampleOrg"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
      LDAP_TLS: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    ports:
      - "389:389"

  vault:
    image: hashicorp/vault:1.15.0
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root_token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

  webapp:
      build:
        context: ./webapp
      container_name: webapp
      ports:
        - "5000:5000"
      depends_on:
        - ldap
        - vault
